using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TranSimCS.Spline;

namespace TranSimCS.Worlds.Paths {
    /// <summary>
    /// An attachment point for a <see cref="SplinePath"/>.
    /// <para>
    /// An attachment point is the thing a path is anchored to. It is deliberately not tied to any
    /// particular road type: a road <see cref="Roads.Node.HalfLane"/>, a building entrance, a parking
    /// bay or a hand-authored spline can all implement this interface and be used as a path endpoint.
    /// </para>
    /// <para>
    /// The attachment point is responsible for producing the geometry of the path it belongs to.
    /// A path with two attachment points is generated by joining them; a path with a single attachment
    /// point is generated by that attachment point alone.
    /// </para>
    /// </summary>
    public interface IPathAttachment {
        /// <summary>
        /// Raised whenever the geometry of this attachment point changes in any way.
        /// <para>
        /// Subscribers must treat this as "the spline may be different now" and regenerate lazily.
        /// The event is also raised when the attachment point is about to become invalid, so that
        /// holders can detach before the underlying object is destroyed.
        /// </para>
        /// </summary>
        public event Action? Changed;

        /// <summary>
        /// The object this attachment point belongs to. Used for ownership, serialization and
        /// for resolving the attachment point back to a world object.
        /// </summary>
        public Obj Owner { get; }

        /// <summary>
        /// Whether this attachment point can still be used to generate a spline.
        /// <para>
        /// This becomes <see langword="false"/> when the object backing the attachment point has been
        /// deleted from the world. A path whose attachment point is not alive must not be used for new
        /// traffic, but may still be referenced by traffic that is already on it.
        /// </para>
        /// </summary>
        public bool IsAlive { get; }

        /// <summary>
        /// The reference frame of this attachment point, in world space.
        /// <para>
        /// The frame's origin is the attachment position, its Z axis points along the direction of
        /// travel away from the attachment point, and its X axis points to the left of travel.
        /// </para>
        /// </summary>
        public Geometry.Transform3 ReferenceFrame { get; }

        /// <summary>
        /// The lateral offset of the attachment point from the reference frame origin, in metres.
        /// <para>
        /// This is the position of the path centre line relative to the attachment point's own
        /// reference frame. It is used to place the path centre line when joining two attachment points.
        /// </para>
        /// </summary>
        public float Offset { get; }

        /// <summary>
        /// Generates the spline for this attachment point.
        /// <para>
        /// The returned spline must be reverse-corrected: it must run in the direction of travel of the
        /// path, regardless of the orientation of the object backing the attachment point.
        /// </para>
        /// </summary>
        /// <returns>The generated spline basis.</returns>
        /// <exception cref="InvalidOperationException">
        /// Thrown when <see cref="IsAlive"/> is <see langword="false"/>.
        /// </exception>
        public OrthodistantBasis GenerateSpline();
    }
}
