using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Clipper2Lib;
using TranSimCS.Geometry.SplineFrames;
using TranSimCS.Model;
using TranSimCS.Polygons;
using TranSimCS.Roads.Strip;

namespace TranSimCS.Roads.RoadRendering {
    /// <summary>
    /// The <see cref="IRoadRenderingStrategy{T}"/> defines how roads are rendered. The interface exposes methods used by the main rendering method,
    /// <see cref="RenderRoad(T, MultiMesh)"/>. Look at the method's documentation for a full explanation of the <b>road rendering pipeline</b>.
    /// Several terms are used widely in this interface:
    /// </summary>
    /// 
    /// <remarks>
    /// <para><b>Polygon</b></para>
    /// A closed path or set of paths, generated by any of these methods. Before the polygon is inteprolated via the <see cref="SplineFrame"/>,
    /// its height is divided by <see cref="CalculatePolygonStretchLength(T)"/>
    /// <list type="bullet">
    ///     <item><see cref="GenerateLaneRangePolygon(LaneRange)"/></item>
    ///     <item><see cref="GenerateOuterBoundary(T)"/></item>
    ///     <item><see cref="GenerateIslands(T)"/></item>
    /// </list>
    /// 
    /// <para><b>Polygon-generating method</b></para>
    /// A method that returns a <b>polygon</b> to be used with a <see cref="SplineFrame"/> returned by <see cref="CalculateSplineFrame(T)"/>
    /// 
    /// <para><b>Road rendering pipeline</b></para>
    /// The entire process used to generate meshes for road segments and sections, from acquiring data to a completed mesh, executed in
    /// <see cref="RenderRoad(T, MultiMesh)"/>
    /// 
    /// <para><b>Road</b></para>
    /// The input data object of type <typeparamref name="T"/> used to generate a mesh for itself.
    /// Each strategy accept different data types.
    /// 
    /// <para><see cref="SplineFrame"/></para>
    /// A data structure containing three splines, <b>O</b>, <b>X</b> and <b>Y</b>, used to interpolate <b>uncorrected road-oriented coordinates</b> to the world/object space
    /// 
    /// <para><b>Road-oriented coordinates</b></para>
    /// A set of coordinates, where X is across to the right, Y is upwards and Z is lengthwise from 0 to <see cref="CalculatePolygonStretchLength(T)"/>
    /// 
    /// <para><b>Uncorrected road-oriented coordinates</b></para>
    /// A set of coordinates, where X is across to the right, Y is upwards and Z is lengthwise from 0 to 1
    /// 
    /// <para><b>Polygon</b></para>
    /// An instance of <see cref="PathD"/>, <see cref="PathsD"/> or <see cref="Polygon"/> in <b>road-oriented coordinates</b>
    /// 
    /// </remarks>
    /// <typeparam name="T"></typeparam>
    public interface IRoadRenderingStrategy<T> {
        /// <summary>
        /// Generates the road mesh for given road. It is a multistep process, starting from acquisition of data
        /// </summary>
        /// <param name="road"></param>
        /// <param name="mesh"></param>
        public void RenderRoad(T road, MultiMesh mesh) {
        }

        /// <summary>
        /// Generates a <see cref="SplineFrame"/> for the given <paramref name="road"/>.
        /// It must be used with polygons generated by <b>polygon-generating methods</b>
        /// </summary>
        /// <param name="road"></param>
        /// <returns></returns>
        public SplineFrame CalculateSplineFrame(T road);
        /// <summary>
        /// Calculates a length over which polygons returned by <b>polygon-generating methods</b> will reach the ends of the <see cref="SplineFrame"/>.
        /// </summary>
        /// <param name="road"></param>
        /// <returns></returns>
        public float CalculatePolygonStretchLength(T road);
        public PathD GenerateLaneRangePolygon(LaneRange laneRange);
        public PathD GenerateOuterBoundary(T road);
        public PathsD GenerateIslands(T road);
        /// <summary>
        /// Retrieves the <see cref="RoadFinish"/> from the supplied road
        /// </summary>
        public RoadFinish? GetRoadFinish(T road);
    }
}
